#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x8A75D10998012C7E (ejb@ql.org)
#
Name     : qpdf
Version  : 8.4.0
Release  : 5
URL      : https://github.com/qpdf/qpdf/releases/download/release-qpdf-8.4.0/qpdf-8.4.0.tar.gz
Source0  : https://github.com/qpdf/qpdf/releases/download/release-qpdf-8.4.0/qpdf-8.4.0.tar.gz
Source99 : https://github.com/qpdf/qpdf/releases/download/release-qpdf-8.4.0/qpdf-8.4.0.tar.gz.asc
Summary  : PDF transformation library
Group    : Development/Tools
License  : Apache-2.0
Requires: qpdf-bin = %{version}-%{release}
Requires: qpdf-lib = %{version}-%{release}
Requires: qpdf-license = %{version}-%{release}
Requires: qpdf-man = %{version}-%{release}
BuildRequires : libjpeg-turbo-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(zlib)

%description
This directory contains sources to the documentation.  If you are
looking for pre-built documentation, please look in the "doc"
directory.

%package bin
Summary: bin components for the qpdf package.
Group: Binaries
Requires: qpdf-license = %{version}-%{release}
Requires: qpdf-man = %{version}-%{release}

%description bin
bin components for the qpdf package.


%package dev
Summary: dev components for the qpdf package.
Group: Development
Requires: qpdf-lib = %{version}-%{release}
Requires: qpdf-bin = %{version}-%{release}
Provides: qpdf-devel = %{version}-%{release}

%description dev
dev components for the qpdf package.


%package doc
Summary: doc components for the qpdf package.
Group: Documentation
Requires: qpdf-man = %{version}-%{release}

%description doc
doc components for the qpdf package.


%package lib
Summary: lib components for the qpdf package.
Group: Libraries
Requires: qpdf-license = %{version}-%{release}

%description lib
lib components for the qpdf package.


%package license
Summary: license components for the qpdf package.
Group: Default

%description license
license components for the qpdf package.


%package man
Summary: man components for the qpdf package.
Group: Default

%description man
man components for the qpdf package.


%prep
%setup -q -n qpdf-8.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550705843
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1550705843
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qpdf
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/qpdf/LICENSE.txt
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fix-qdf
/usr/bin/qpdf
/usr/bin/zlib-flate

%files dev
%defattr(-,root,root,-)
/usr/include/qpdf/Buffer.hh
/usr/include/qpdf/BufferInputSource.hh
/usr/include/qpdf/ClosedFileInputSource.hh
/usr/include/qpdf/Constants.h
/usr/include/qpdf/DLL.h
/usr/include/qpdf/FileInputSource.hh
/usr/include/qpdf/InputSource.hh
/usr/include/qpdf/JSON.hh
/usr/include/qpdf/Pipeline.hh
/usr/include/qpdf/Pl_Buffer.hh
/usr/include/qpdf/Pl_Concatenate.hh
/usr/include/qpdf/Pl_Count.hh
/usr/include/qpdf/Pl_DCT.hh
/usr/include/qpdf/Pl_Discard.hh
/usr/include/qpdf/Pl_Flate.hh
/usr/include/qpdf/Pl_QPDFTokenizer.hh
/usr/include/qpdf/Pl_RunLength.hh
/usr/include/qpdf/Pl_StdioFile.hh
/usr/include/qpdf/PointerHolder.hh
/usr/include/qpdf/QPDF.hh
/usr/include/qpdf/QPDFAcroFormDocumentHelper.hh
/usr/include/qpdf/QPDFAnnotationObjectHelper.hh
/usr/include/qpdf/QPDFDocumentHelper.hh
/usr/include/qpdf/QPDFExc.hh
/usr/include/qpdf/QPDFFormFieldObjectHelper.hh
/usr/include/qpdf/QPDFNameTreeObjectHelper.hh
/usr/include/qpdf/QPDFNumberTreeObjectHelper.hh
/usr/include/qpdf/QPDFObjGen.hh
/usr/include/qpdf/QPDFObject.hh
/usr/include/qpdf/QPDFObjectHandle.hh
/usr/include/qpdf/QPDFObjectHelper.hh
/usr/include/qpdf/QPDFOutlineDocumentHelper.hh
/usr/include/qpdf/QPDFOutlineObjectHelper.hh
/usr/include/qpdf/QPDFPageDocumentHelper.hh
/usr/include/qpdf/QPDFPageLabelDocumentHelper.hh
/usr/include/qpdf/QPDFPageObjectHelper.hh
/usr/include/qpdf/QPDFSystemError.hh
/usr/include/qpdf/QPDFTokenizer.hh
/usr/include/qpdf/QPDFWriter.hh
/usr/include/qpdf/QPDFXRefEntry.hh
/usr/include/qpdf/QTC.hh
/usr/include/qpdf/QUtil.hh
/usr/include/qpdf/RandomDataProvider.hh
/usr/include/qpdf/Types.h
/usr/include/qpdf/qpdf-c.h
/usr/lib64/libqpdf.so
/usr/lib64/pkgconfig/libqpdf.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/qpdf/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libqpdf.so.21
/usr/lib64/libqpdf.so.21.4.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qpdf/LICENSE.txt

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/fix-qdf.1
/usr/share/man/man1/qpdf.1
/usr/share/man/man1/zlib-flate.1
